#===========================================================================
#
# Hub Messages that we don't understand.
#
#===========================================================================
from .Base import Base


class HubRFUnknown(Base):
    """This message appears twice in a row roughly every 30 minutes.

    The messages in the 0x79+ range are RF commands sent to the modem.
    This 0x7f message is not documented anywhere and doesn't seem to do
    anything that can be detected. The message is likely generated by the Host
    on the Hub and we are only seeing the modem response.

    The first time the message is sent byte_3 seems to always be set to 0x02
    and then a few seconds later the same message is sent with byte_3 = 0x00
    """
    # pylint: disable=abstract-method

    msg_code = 0x7f
    # The messages we see are almost certainly an ack as the last byte is
    # always 0x06.
    fixed_msg_size = 4

    #-----------------------------------------------------------------------
    @classmethod
    def from_bytes(cls, raw):
        """Read the message from a byte stream.

        This should only be called if raw[1] == msg_code and len(raw) >=
        msg_size().

        Args:
          raw (bytes):  The current byte stream to read from.

        Returns:
          Returns the constructed InpUserSetBtn object.
        """
        assert len(raw) >= HubRFUnknown.fixed_msg_size
        assert raw[0] == 0x02 and raw[1] == HubRFUnknown.msg_code

        return HubRFUnknown(raw[2])

    #-----------------------------------------------------------------------
    def __init__(self, byte_3):
        """Constructor

        Args:
          byte_3 (int):  This is the only payload byte in this message.
        """
        super().__init__()

        # Saving this, but no idea what it means
        self.byte_3 = byte_3

    #-----------------------------------------------------------------------
    def __str__(self):
        return "Hub RF Unknown: %s" % self.byte_3

    #-----------------------------------------------------------------------

#===========================================================================
